CREATE STREAM count_input_stream (COUNT BIGINT, CATEGORY VARCHAR) WITH (KAFKA_TOPIC = 'test_avro', KEY_FORMAT = 'KAFKA', VALUE_FORMAT = 'AVRO');


CREATE TABLE average_count_table WITH (KAFKA_TOPIC='avg_count_topic', KEY_FORMAT='KAFKA', VALUE_FORMAT='JSON', PARTITIONS=1, REPLICAS=3)
AS SELECT WINDOWSTART as start_time, WINDOWEND as end_time, AVG(COUNT) AS avg_count, CATEGORY FROM count_input_stream WINDOW TUMBLING (SIZE 10 SECONDS)
GROUP BY CATEGORY;

SELECT * FROM average_count_table;
